/*
  Warnings:

  - The values [LOGIN,CREATE_ALERT,SEND_ALERT,CANCEL_ALERT,UPDATE_ALERT,CREATE_USER,UPDATE_USER,DELETE_USER,CREATE_AGENCY,UPDATE_AGENCY,DELETE_AGENCY,REGISTER_CITIZEN,UPDATE_CITIZEN] on the enum `ActionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActionType_new" AS ENUM ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'LOGOUT_ALL', 'TOKEN_REFRESH', 'SESSION_REVOKED', 'PASSWORD_CHANGE', 'PASSWORD_CHANGE_FAILED', 'PASSWORD_RESET', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'AGENCY_CREATED', 'AGENCY_UPDATED', 'AGENCY_DELETED', 'AGENCY_ACTIVATED', 'AGENCY_SUSPENDED', 'ALERT_CREATED', 'ALERT_UPDATED', 'ALERT_SENT', 'ALERT_CANCELLED', 'ALERT_EXPIRED', 'ALERT_VIEWED', 'CITIZEN_REGISTERED', 'CITIZEN_UPDATED', 'CITIZEN_OPTED_IN', 'CITIZEN_OPTED_OUT', 'CITIZEN_DELETED', 'SYSTEM_CONFIG_CHANGED', 'BACKUP_CREATED', 'BACKUP_RESTORED', 'SUSPICIOUS_ACTIVITY', 'UNAUTHORIZED_ACCESS_ATTEMPT', 'DATA_EXPORT', 'DATA_IMPORT', 'OTHER');
ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "ActionType_new" USING ("action"::text::"ActionType_new");
ALTER TYPE "ActionType" RENAME TO "ActionType_old";
ALTER TYPE "ActionType_new" RENAME TO "ActionType";
DROP TYPE "public"."ActionType_old";
COMMIT;
