-- CreateEnum
CREATE TYPE "USSDStep" AS ENUM ('START', 'MAIN_MENU', 'REGISTER_LANGUAGE', 'REGISTER_FIRSTNAME', 'REGISTER_LASTNAME', 'REGISTER_STATE', 'REGISTER_LGA', 'REGISTER_WARD', 'REGISTER_CONFIRM', 'UNSUBSCRIBE_CONFIRM', 'HELP');
