version = 5.3.1
archive_dir = /etc/letsencrypt/archive/api.geoalert.xyz
cert = /etc/letsencrypt/live/api.geoalert.xyz/cert.pem
privkey = /etc/letsencrypt/live/api.geoalert.xyz/privkey.pem
chain = /etc/letsencrypt/live/api.geoalert.xyz/chain.pem
fullchain = /etc/letsencrypt/live/api.geoalert.xyz/fullchain.pem
[renewalparams]
account = 2872268b106d1a52efc26ce2abdca5a2
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.geoalert.xyz = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-03-04T18:15:31
