/*
  Warnings:

  - The values [TWO_FA_METHOD_CHANGED] on the enum `ActionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActionType_new" AS ENUM ('LOGIN_PENDING_2FA', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'LOGOUT_ALL', 'TOKEN_REFRESH', 'SESSION_REVOKED', 'PASSWORD_CHANGE', 'PASSWORD_CHANGE_FAILED', 'PASSWORD_RESET', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'AGENCY_CREATED', 'AGENCY_UPDATED', 'AGENCY_DELETED', 'AGENCY_ACTIVATED', 'AGENCY_SUSPENDED', 'ALERT_CREATED', 'ALERT_UPDATED', 'ALERT_SENT', 'ALERT_FAILED', 'ALERT_CANCELLED', 'ALERT_EXPIRED', 'ALERT_VIEWED', 'CITIZEN_REGISTERED', 'CITIZEN_UPDATED', 'CITIZEN_OPTED_IN', 'CITIZEN_OPTED_OUT', 'CITIZEN_DELETED', 'SYSTEM_CONFIG_CHANGED', 'BACKUP_CREATED', 'BACKUP_RESTORED', 'SUSPICIOUS_ACTIVITY', 'UNAUTHORIZED_ACCESS_ATTEMPT', 'DATA_EXPORT', 'DATA_IMPORT', 'TWO_FA_SETUP_INITIATED', 'TWO_FA_SETUP_FAILED', 'TWO_FA_ENABLED', 'TWO_FA_DISABLED', 'TWO_FA_VERIFICATION_SUCCESS', 'TWO_FA_VERIFICATION_FAILED', 'EMAIL_OTP_SENT', 'BACKUP_CODE_USED', 'BACKUP_CODES_REGENERATED', 'OTHER');
ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "ActionType_new" USING ("action"::text::"ActionType_new");
ALTER TYPE "ActionType" RENAME TO "ActionType_old";
ALTER TYPE "ActionType_new" RENAME TO "ActionType";
DROP TYPE "public"."ActionType_old";
COMMIT;
