export const cacheConstants = {
  keys: {
    USER: {
      BY_ID: "user:id",
      BY_EMAIL: "user:email",
      SESSIONS: "user:sessions",
      PERMISSIONS: "user:permissions",
      PROFILE: "user:profile",
    },
    CITIZEN: {
      BY_ID: "citizen:id",
      BY_PHONE: "citizen:phone",
      LIST: "citizen:list",
      STATS: "citizen:stats",
      NEARBY: "citizen:nearby",
      BY_LOCATION: "citizen:location",
      COUNT: "citizen:count",
    },
    AGENCY: {
      BY_ID: "agency:id",
      BY_NAME: "agency:name",
      LIST: "agency:list",
      STATS: "agency:stats",
      USERS: "agency:users",
      NEMA_ID: "agency:nema_id",
    },
    ALERT: {
      BY_ID: "alert:id",
      ACTIVE: "alert:active",
      BY_AGENCY: "alert:agency",
      BY_JURISDICTION: "alert:jurisdiction",
      STATS: "alert:stats",
      LIST: "alert:list",
      TOTP_SETUP: "auth:totp:setup",
      EMAIL_OTP: "auth:email:otp",
      EMAIL_OTP_COOLDOWN: "auth:email:otp:cooldown",
      TWO_FA_ATTEMPTS: "auth:2fa:attempts",
    },
    USSD: {
      SESSION: "ussd:session",
    },
    LOCATION: {
      STATE: "location:state",
      LGA: "location:lga",
      WARD: "location:ward",
      HIERARCHY: "location:hierarchy",
    },
    AUTH: {
      REFRESH_TOKEN: "auth:refresh",
      TOTP_SETUP: "auth:totp:setup",
      EMAIL_OTP: "auth:email:otp",
      EMAIL_OTP_COOLDOWN: "auth:email:otp:cooldown",
      TWO_FA_ATTEMPTS: "auth:2fa:attempts",
      LOGIN_ATTEMPTS: "auth:login:attempts",
      TOKEN_BLACKLIST: "auth:token:blacklist",
      PASSWORD_RESET_TOKEN: "auth:password:reset:token",
      EMAIL_SETUP: "auth:email:setup",
      EMAIL_SETUP_OTP: "auth:email:setup:otp",
      EMAIL_SETUP_COOLDOWN: "auth:email:setup:cooldown",
      EMAIL_SETUP_ATTEMPTS: "auth:email:setup:attempts",
      EMAIL_SETUP_LOCKOUT: "auth:email:setup:lockout",
      EMAIL_OTP_HOURLY: "auth:email:otp:hourly",
      ACTIVATION_TOKEN: "activation:token",
    },
    BFF: {
      SESSION: "bff:session",
      USER_SESSIONS: "bff:user:sessions",
      TEMP_2FA_SESSION: "bff:temp:2fa",
      DEVICE_FINGERPRINT: "bff:device:fingerprint",
    },
    REFERENCE: {
      STATES: "ref:states",
      LGAS: "ref:lgas",
      WARDS: "ref:wards",
    },
    SMS: {
      DELIVERY_STATUS: "sms:delivery_status",
      TRANSACTIONAL: "sms:transactional",
    },
    HEALTH: {
      STATUS: "health:status",
    },
  },

  ttl: {
    VERY_SHORT: 60,
    SHORT: 300,
    MEDIUM: 900,
    MEDIUM_LONG: 1800,
    LONG: 3600,
    VERY_LONG: 21600,
    DAY: 86400,
    WEEK: 604800,
    USER_SESSION: 900,
    USER_DATA: 1800,
    AGENCY_DATA: 3600,
    AGENCY_STATS: 300,
    ALERT_ACTIVE: 60,
    ALERT_HISTORY: 3600,
    LOCATION_DATA: 86400,
    CITIZEN_DATA: 1800,
    TOKEN_BLACKLIST: 900,
    LOGIN_ATTEMPTS: 900,
    BFF_SESSION: 86400,
    BFF_SESSION_IDLE: 7200,
    BFF_TEMP_2FA: 300,
    BFF_DEVICE_FINGERPRINT: 2592000,
  },
};